In [6]:
pip install cassandra-driver #install driver for casandrapip install dse-driver

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#install'

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import cassandra; print (cassandra.__version__) #test installations

3.28.0

In [9]:
import dse

ModuleNotFoundError: No module named 'dse'

In [4]:
print(dse.__version__)

2.11.1

In [1]:
#conncet_Database.py

from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
cloud_config= {
  'secure_connect_bundle': './db/secure-connect-db-census-income.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("./db/db_census_income-token.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
session = cluster.connect('keyspace_census')

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

4.0.0.6816

In [6]:
session.execute(
    'CREATE TABLE census_income (id int AUTO_INCREMENT,education text, occupation text, age int, capital_gain int, capital_loss int, education_num int, fiftyplus bool, fnlwgt int, hours_per_week int, marital_status text, native_country text, race text, relationship text, sex text, workclass text, PRIMARY KEY (id))')

SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:35 no viable alternative at input 'AUTO_INCREMENT' (CREATE TABLE census_income (id [int] AUTO_INCREMENT...)">

In [20]:

# Create a table.
session.execute('CREATE TABLE user_test (id int, name text, age int, PRIMARY KEY (id))')

In [21]:
query = "SELECT * FROM user_test;"

results = session.execute(query)

for row in results:
  print(row)

In [22]:

session.execute(
    """
    INSERT INTO user_test (id,name, age)
    VALUES (%s, %s, %s)
    """,
    (1,"John O'Reilly", 42)
)

In [23]:
session.execute(
    """
    INSERT INTO user_test (id,name, age)
    VALUES (%s, %s, %s)
    """,
    (2,"abc", 32)
)

In [24]:
session.execute(
    """
    INSERT INTO user_test (id,name, age)
    VALUES (%s, %s, %s)
    """,
    (3,"AGH", 47)
)

In [2]:
query = "SELECT * FROM income_cleaned;"

results = session.execute(query)

for row in results:
  print(row)
  # print(row.id)

InvalidRequest: Error from server: code=2200 [Invalid query] message="table keyspace_census.income_cleaned does not exist"

In [36]:
# Close the Session object.
session.shutdown()

# Close the Cluster object.
cluster.shutdown()